Controllers/CenterController.cs
using conectArte.Datos;
using conectArte.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace conectArte.Controllers
{
    public class CenterController : Controller
    {
        private readonly ApplicationDBContext _context;

        public CenterController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult AddCenter()
        {
            List<Coordinator> coordinators = _context.Coordinators.ToList();
            ViewData["Coordinators"] = coordinators;
            return View();
        }

        [HttpPost]
        public IActionResult AddCenter(Center c)
        {
            _context.Centers.Add(c);
            _context.SaveChanges();
            return RedirectToAction("ListCenter");
        }

        public IActionResult ListCenter()
        {
            List<Center> centers = _context.Centers
                .Include(t => t.Coordinator)
                .ToList();
            return View(centers);
        }

        public IActionResult DeleteCenter(int id)
        {
            Center t = _context.Centers.Find(id);
            _context.Centers.Remove(t);
            _context.SaveChanges();
            return RedirectToAction("ListCenter");
        }

        public IActionResult CenterDetails(int id)
        {
            Center c = _context.Centers.Include(c => c.Coordinator)
                        .FirstOrDefault(c => c.Id == id);
            return View(c);
        }

        public IActionResult UpdateCenter(int id)
        {
            Center t = _context.Centers.Find(id);
            List<Coordinator> coordinators = _context.Coordinators.ToList();
            ViewData["Coordinators"] = coordinators;    
            return View(t);
        }

        [HttpPost]
        public IActionResult UpdateCenter(Center t)
        {
            _context.Centers.Update(t);
            _context.SaveChanges();
            return RedirectToAction("ListCenter");
        }
    }
}

Controllers/FilterController.cs
using conectArte.Datos;
using conectArte.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Cryptography;

namespace conectArte.Controllers
{
    public class FilterController : Controller
    {
        private readonly ApplicationDBContext _context;
        public FilterController(ApplicationDBContext context)
        {
            this._context = context;
        }

        public IActionResult NoResourceWorkshopAssistants()
        {
            List<Workshop> workshops = _context.Workshops
                .Where(w => w.Room.ResourcesRooms.Any())
                .ToList();

            List<WorkshopAssistant> workasst = _context.WorkshopAssistants
                .Include(aw => aw.Assistant)
                .Include(w => w.Workshop)
                .Where(w =>!workshops.Contains(w.Workshop))
                .ToList();

            List<Assistant> assistant = new List<Assistant>();

            if (workasst.Count > 0)
            {
                
                foreach(WorkshopAssistant wa in workasst)
                {
                    assistant.Add(wa.Assistant);
                }
            }

            return View(assistant);
        }


        public IActionResult AssistantsForWorkshopAttendance()
        {
            List<Assistant> assistants = _context.Assistants
                .Include(a => a.Center)
                .Include(a => a.WorkshopsAttended)
                    .ThenInclude(aw => aw.Workshop)
                .Where(a => a.WorkshopsAttended.Count > 0)
                .OrderByDescending(aa => aa.WorkshopsAttended.Count())
                .Take(5)
                .ToList();            
            return View(assistants);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RoomController.cs
using conectArte.Datos;
using conectArte.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace conectArte.Controllers
{
    public class RoomController : Controller
    {
        private readonly ApplicationDBContext _context;

        public RoomController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult AddRoom()
        {
            ViewData["Centers"] = _context.Centers.ToList();
            ViewData["Resources"] = _context.Resources.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult AddRoom(Room r)
        {
            try
            {
                /*if (_context.Rooms.Any(ro => ro.Name == r.Name))
                {
                    ModelState.AddModelError("Name", "El identificador ya existe");
                    return View(r);
                }

                if (!ModelState.IsValid)
                {
                    return View(r);
                }*/
                _context.Rooms.Add(r);
                _context.SaveChanges();
                foreach (int i in r.ResourcesIds)
                {
                    ResourceRoom rr = new ResourceRoom
                    {
                        ResourceId = i,
                        RoomName = r.Name,
                        ResourceCount = 1
                    };
                    _context.Add(rr);
                }
                _context.SaveChanges();
                return RedirectToAction("ListRoom");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError ("", "Error interno del sistema");
                return View(r);
            }
        }

        public IActionResult ListRoom()
        {
            List<Room> rooms = _context.Rooms
                .Include(r => r.Center)
                .ToList();
            return View(rooms);
        }

        public IActionResult DeleteRoom(int id)
        {
            Room r = _context.Rooms.Find(id);
            _context.Rooms.Remove(r);
            _context.SaveChanges();
            return RedirectToAction("ListRoom");
        }

        public IActionResult RoomDetails(string name)
        {
            Room r = _context.Rooms.Include(r => r.Center)
                                    .Include(r => r.ResourcesRooms)
                                    .ThenInclude(rr => rr.AssignedResource)
                                    .FirstOrDefault(r => r.Name == name);
            return View(r);
        }

        public IActionResult UpdateRoom(string name)
        {
            Room r = _context.Rooms.Include(r => r.ResourcesRooms)
                            .FirstOrDefault(r => r.Name == name);
            List<Center> centers = _context.Centers.ToList();
            ViewData["Centers"] = centers;
            List<Resource> resources = _context.Resources.ToList();
            ViewData["Resources"] = resources;
            return View(r);
        }

        [HttpPost]
        public IActionResult UpdateRoom(Room r)
        {
            _context.Rooms.Update(r);
            _context.SaveChanges();

            List<ResourceRoom> previous = _context.Set<ResourceRoom>()
                .Where(rr => rr.RoomName == r.Name)
                .ToList();
            _context.Set<ResourceRoom>().RemoveRange(previous);
            _context.SaveChanges();

            if(r.ResourcesIds != null)
            {
                foreach(int id in r.ResourcesIds)
                {
                    ResourceRoom rr = new ResourceRoom { ResourceId = id, RoomName = r.Name};
                    _context.Add(rr);
                }
                _context.SaveChanges();
            }
            return RedirectToAction("ListRoom");
        }

        [HttpPost]
        public IActionResult DeleteAssignedResource(string roomName, int id)
        {
            ResourceRoom resroom = _context.Set<ResourceRoom>()
                        .FirstOrDefault(rr => rr.RoomName == roomName && rr.ResourceId == id);
            if(resroom != null)
            {
                _context.Set<ResourceRoom>().Remove(resroom);
                _context.SaveChanges();
            }
            return RedirectToAction("RoomDetails", new { name = roomName });
        }

        [HttpPost]
        public IActionResult UpdateAssignedResourceCount(string roomName, int ResourceId, int ResourceCount)
        {
            ResourceRoom rsm = _context.Set<ResourceRoom>()
                 .FirstOrDefault(rr => rr.RoomName == roomName && rr.ResourceId == ResourceId);
            rsm.ResourceCount = ResourceCount;
            _context.ResourceRooms.Update(rsm);
            _context.SaveChanges();
            return RedirectToAction("RoomDetails", new { name = rsm.RoomName });
        }
    }
}

Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using conectArte.Datos;
using conectArte.Models;

namespace conectArte.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ApplicationDBContext _context;

        public TeacherController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult AddTeacher()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddTeacher(Teacher t)
        {

            if (!ModelState.IsValid)
            {
                return View(t);
            }
            _context.Teachers.Add(t);
            _context.SaveChanges();
            return RedirectToAction("ListTeacher");
        }

        public IActionResult ListTeacher()
        {
            List<Teacher> t = _context.Teachers.ToList();
            return View(t);
        }

        public IActionResult DeleteTeacher(int id)
        {
            Teacher t = _context.Teachers.Find(id);
            _context.Teachers.Remove(t);
            _context.SaveChanges();
            return RedirectToAction("ListTeacher");
        }

        public IActionResult UpdateTeacher(int id)
        {
            Teacher t = _context.Teachers.Find(id);
            return View(t);
        }

        [HttpPost]
        public IActionResult UpdateTeacher(Teacher t)
        {
            _context.Teachers.Update(t);
            _context.SaveChanges();
            return RedirectToAction("ListTeacher");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ConectArte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/conectArte.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid" id="navbarSupportedContent">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">conectArte</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex gap-3">
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Docentes</option>
                        <option value="@Url.Action("AddTeacher", "Teacher")">Agregar docente</option>
                        <option value="@Url.Action("ListTeacher", "Teacher")">Listar docentes</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Coordinadores</option>
                        <option value="@Url.Action("AddCoordinator", "Coordinator")">Alta coordinador</option>
                        <option value="@Url.Action("ListCoordinator", "Coordinator")">Listar Coordinadores</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Centros</option>
                        <option value="@Url.Action("AddCenter", "Center")">Alta centro</option>
                        <option value="@Url.Action("ListCenter", "Center")">Listar centros</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Salas</option>
                        <option value="@Url.Action("AddRoom", "Room")">Alta sala</option>
                        <option value="@Url.Action("ListRoom", "Room")">Listar salas</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Recursos</option>
                        <option value="@Url.Action("AddResource", "Resource")">Alta recurso</option>
                        <option value="@Url.Action("ListResource", "Resource")">Listar recursos</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Talleres</option>
                        <option value="@Url.Action("AddWorkshop", "Workshop")">Alta Taller</option>
                        <option value="@Url.Action("ListWorkshop", "Workshop")">Listar Talleres</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Asistentes</option>
                        <option value="@Url.Action("AddAssistant", "Assistant")">Alta Asistente</option>
                        <option value="@Url.Action("ListAssistant", "Assistant")">Listar Asistentes</option>
                    </select>
                    <select style="width: 150px; border: none" class="form-select" onchange="location = this.value;">
                        <option selected disabled>Filtros</option>
                        <option value="@Url.Action("NoResourceWorkshopAssistants", "Filter")">Lista asistentes a talleres sin recursos</option>
                        <option value="@Url.Action("AssistantsForWorkshopAttendance", "Filter")">Listar asistentes con más talleres realizados</option>
                    </select>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - conectArte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>